name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with Node.js
        run: |
          node build.js
          # Create the static directory structure
          mkdir -p build/static/{css,js,images,fonts}
          
          # Copy all static files
          cp -r static/* build/static/
          
          # Copy root files
          cp index.html build/
          cp 404.html build/
          cp robots.txt build/
          
          # Debug: List build directory contents
          echo "Build directory structure:"
          find build -type f | sort
          
      - name: Verify Build Output
        run: |
          # Check if required files exist
          if [ ! -f "build/index.html" ]; then
            echo "::error::index.html not found in build directory"
            exit 1
          fi
          if [ ! -f "build/static/css/style.css" ]; then
            echo "::error::style.css not found in build/static/css/"
            exit 1
          fi
          echo "Build verification passed!"
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: "."
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
